# Generated by Django 2.0.5 on 2018-06-22 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_shopcar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcar',
            name='user',
        ),
    ]
