"""empty message

Revision ID: 391a3502e8c6
Revises: 566d6e3f3653
Create Date: 2018-06-05 20:29:20.925212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391a3502e8c6'
down_revision = '566d6e3f3653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('rid', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=60), nullable=True),
    sa.Column('recipe', sa.TEXT(), nullable=True),
    sa.Column('createdtime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('rid')
    )
    # ### end Alembic commands ###
