# Generated by Django 2.0.5 on 2018-05-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='uaddress',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ushou',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='uyoubian',
        ),
    ]
